### ISSUE TITLE
Upgrade to version 4.9.26 breaks network connection between Linux and Windows pods

### ISSUE THREAD

**Issue by SSvilen** [openshift/windows-machine-config-operator#1031]
**Describe the bug**
We noticed that after upgrade to 4.9.26 we lost connectivity between Linux and Windows pods (both directions). The pods however are able to communicate with external networks.
The problem affects 2 different clusters after upgrade, so it can’t be coincidence. 

1. WMCO & OpenShift Version - 4.0.1 & 4.9.26 
2. Platform - vSphere

Are you aware of any issues. In case logs are required, we could provide them.

**Comment by sebsoto** [comment]
Hi @SSvilen,
Is this an issue specific to Windows workloads running during the upgrade process? Does restarting the pods fix this issue, or are you finding that all Windows pods on OCP 4.9.26 have this issue?

**Comment by selansen** [comment]
pls post the support ticket here for reference and close this one if it is not related to WMCO.

**Comment by SSvilen** [comment]
@selansen,

Sorry I was on a vacation. 
Case 03200229

I can confirm that reinstalling the cluster with version 4.9.25 resolved the problem. 
We've disabled the upgrades for the time being.

**Comment by jrvaldes** [comment]
/close

[BZ#2084098](https://bugzilla.redhat.com/show_bug.cgi?id=2084098) is tracking this issue with Network Team.
