### ISSUE TITLE
Support for for Windows Server 2022

### ISSUE THREAD

**Issue by burkhat** [openshift/windows-machine-config-operator#1095]
Hello together,

since a few months following ticket is closed: https://issues.redhat.com/browse/WINC-602 

But since then we got no update when the new Version of WMCO is available to support Windows Server 2022.

Do you have any updates?

Regards
Tobias

**Comment by saifshaikh48** [comment]
Windows Server 2022 support on vSphere and platform agnostic clusters/baremetal is coming in WMCO 5.1.0 (OCP 4.10). GA scheduled for next week.

Windows Server 2022 support on AWS and Azure is planned for WMCO 6.0.0, releasing when OCP 4.11 comes out.

Best,
Mohammad

**Comment by burkhat** [comment]
Hello Mohammad, 
Thanks for your reply.
I am looking forward to trying the new version
