### ISSUE TITLE
Bootstrap in vSphere Environment Fails if Windows Defender Feature is not Installed 

### ISSUE THREAD

**Issue by MattPOlson** [openshift/windows-machine-config-operator#1107]
**Describe the bug**
In a vSphere environment if the Windows Defender Feature is not Installed in the golden image the operator fails to bootstrap the node. It tries to configure the windows defender exclusion for the containerd service by calling Add-MpPreference. Add-MpPreference is only available if the Windows Defender Feature is installed.

`1.656434951067332e+09 DEBUG wc 10.33.154.128 setting Windows defender exclusion failed {"command": "Add-MpPreference -ExclusionProcess C:\\k\\containerd\\containerd.exe", "output": "Add-MpPreference : The term 'Add-MpPreference' is not recognized as the name of a cmdlet, function, script file, or \r\noperable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try \r\nagain.\r\nAt line:1 char:1\r\n+ Add-MpPreference -ExclusionProcess C:\\k\\containerd\\containerd.exe\r\n+ ~~~~~~~~~~~~~~~~\r\n + CategoryInfo : ObjectNotFound: (Add-MpPreference:String) [], CommandNotFoundException\r\n + FullyQualifiedErrorId : CommandNotFoundException\r\n \r\n"}`

**To Reproduce**
1. Configure a golden image without the Windows Defender feature installed.
2. Create a machine set to use this image and scale it to 1
3. Monitor the logs of the operator pod and the error above will be thrown.

**Expected behavior**
If the Windows Defender Feature is not installed the operator should not try to set the exclusion.

**Comment by mansikulkarni96** [comment]
Closing this issue as the PR linked above has been merged and the issue has been addressed.
/close
