### ISSUE TITLE
Configure Nodes to Access Secure Registries

### ISSUE THREAD

**Issue by MattPOlson** [openshift/windows-machine-config-operator#1124]
This is a feature request for the following. With the current version of the operator that uses containerd the toml file at C:\k\containerd on each of the nodes needs to be modified to allow auth to the private registry. Currently every time a windows node is provisioned there is a manual step to allow it to pull from the registry. If the operator could read from the same secret that the coreos nodes use and  configure the toml file on the nodes this would eliminate the manual step currently needed. Below is an example of the config file to allow access.

```    [plugins."io.containerd.grpc.v1.cri".registry]
      config_path = ""

      [plugins."io.containerd.grpc.v1.cri".registry.auths]

      [plugins."io.containerd.grpc.v1.cri".registry.configs]
        [plugins."io.containerd.grpc.v1.cri".registry.configs."my-registry.com".auth]
          auth = "*************"

      [plugins."io.containerd.grpc.v1.cri".registry.headers]

**Comment by jrvaldes** [comment]
@MattPOlson, [WINC-846](https://issues.redhat.com/browse/WINC-846) was created to track this work.

**Comment by sebsoto** [comment]
Keeping this open so its tracked on Github as well
