### ISSUE TITLE
[Bug]:  Check if Defender is running is wrong

### ISSUE THREAD

**Issue by SSvilen** [openshift/windows-machine-config-operator#1240]
### Attention

- [X] I am using the community version of WMCO

### Version

OCP

### Cluster Version

4.11

### Platform

vSphere

### Proxy

Yes, without HTTPS

### WMCO Version

6.0.0

### Windows version

2022

### What happened?

The check, whether or not Defender is running is wrong. [SourceCode](https://github.com/openshift/windows-machine-config-operator/blob/5928b620ee7fdf3d1328e7d393ea8c6f467616c3/pkg/windows/windows.go#L1025)
The Defender Services are always there, so that check returns always "true".
As [mentioned in the Microsoft documentation](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/microsoft-defender-antivirus-compatibility?view=o365-worldwide#use-windows-powershell-to-confirm-that-microsoft-defender-antivirus-is-running), it must be checked whether the process is running. 

That line needs to be changed to 
```powershell
Get-Process | where-object Name -eq 'MsMpEng.exe'
```

This is the result from the current command on a server where Defender DOES NOT run:
```powershell
PS > (Get-Service | where {$_.DisplayName -Like 'Windows Defender*'}) | ft  -AutoSize

Status  Name   DisplayName
------  ----   -----------
Running mpssvc Windows Defender Firewall
Stopped Sense  Windows Defender Advanced Threat Protection Service
```

And the logs from the operator:

```
{"level":"error","ts":1662711753.9641004,"logger":"wc __IP__","msg":"error running","cmd":"powershell.exe -NonInteractive -ExecutionPolicy Bypass \"Add-MpPreference -ExclusionProcess C:\\k\\containerd\\containerd.exe\"","out":"Add-MpPreference : The term 'Add-MpPreference' is not recognized as the name of a cmdlet, function, script file, or \r\noperable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try \r\nagain.\r\nAt line:1 char:1\r\n+ Add-MpPreference -ExclusionProcess C:\\k\\containerd\\containerd.exe\r\n+ ~~~~~~~~~~~~~~~~\r\n    + CategoryInfo          : ObjectNotFound: (Add-MpPreference:String) [], CommandNotFoundException\r\n    + FullyQualifiedErrorId : CommandNotFoundException\r\n \r\n","error":"Process exited with status 1","stacktrace":"github.com/openshift/windows-machine-config-operator/pkg/windows.(*windows).createWindowsDefenderExclusion\n\t/remote-source/build/windows-machine-config-operator/pkg/windows/windows.go:1056\ngithub.com/openshift/windows-machine-config-operator/pkg/windows.(*windows).configureContainerd\n\t/remote-source/build/windows-machine-config-operator/pkg/windows/windows.go:455\ngithub.com/openshift/windows-machine-config-operator/pkg/windows.(*windows).Configure\n\t/remote-source/build/windows-machine-config-operator/pkg/windows/windows.go:436\ngithub.com/openshift/windows-machine-config-operator/pkg/nodeconfig.(*nodeConfig).Configure\n\t/remote-source/build/windows-machine-config-operator/pkg/nodeconfig/nodeconfig.go:197\ngithub.com/openshift/windows-machine-config-operator/controllers.(*instanceReconciler).ensureInstanceIsUpToDate\n\t/remote-source/build/windows-machine-config-operator/controllers/controllers.go:91\ngithub.com/openshift/windows-machine-config-operator/controllers.(*ConfigMapReconciler).ensureInstancesAreUpToDate\n\t/remote-source/build/windows-machine-config-operator/controllers/configmap_controller.go:293\ngithub.com/openshift/windows-machine-config-operator/controllers.(*ConfigMapReconciler).reconcileNodes\n\t/remote-source/build/windows-machine-config-operator/controllers/configmap_controller.go:258\ngithub.com/openshift/windows-machine-config-operator/controllers.(*ConfigMapReconciler).Reconcile\n\t/remote-source/build/windows-machine-config-operator/controllers/configmap_controller.go:153\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/remote-source/build/windows-machine-config-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:121\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/remote-source/build/windows-machine-config-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:320\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/remote-source/build/windows-machine-config-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:273\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/remote-source/build/windows-machine-config-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:234"}
```

As you can see the defender module is not present at all on our servers. 

We do not use community version of the operator, but I believe this issue should be visible here..

### What did you expect to happen?

The check whether or not the defender is installed should not be based on the number of services.

### Steps to reproduce the issue

Install a server and disable Defender. 

### Do you have a workaround for this issue?

Created a "fake" powershell module with an empty defender pscmdlet...
But it can not be a solution for our production environment.
It's an absolute show stopper for our migration to 2022.

**Comment by mansikulkarni96** [comment]
thanks for opening up the issue @SSvilen, we will make this a part of our next grooming.

**Comment by MattPOlson** [comment]
We ran into this problem also and I opened the original bug for it. I found that if the Windows Defender feature was not installed then the module isn't there. But if the feature is installed then the module is there, I was able to work around it by just installing the windows feature and then disabling the firewall. I think this would be a good way to determine if the feature is there or not.

`PS C:\Users\Administrator> get-WindowsFeature Windows-Defender | Select-Object -ExpandProperty installstate
Installed`

Here is the status on the service on on of our machines where it's working

 (Get-Service | where {$_.DisplayName -Like 'Windows Defender*'}) | ft  -AutoSize

Status  Name   DisplayName                                                                                                                                                                                                                   ------  ----   -----------                                                                                                                                                                                                                   Running mpssvc Windows Defender Firewall                                                                                                                                                                                                     Stopped Sense  Windows Defender Advanced Threat Protection Service                                                                                                                                                                                                                                                                                                                                                                                                                        
PS C:\Users\Administrator> Add-MpPreference

**Comment by SSvilen** [comment]
@mansikulkarni96  any news here? I would really like to have this fixed and avoid using workarounds.

**Comment by mansikulkarni96** [comment]
@SSvilen yes there is a bug created in our backlog to tackle this https://issues.redhat.com/browse/OCPBUGS-1513
If this issue is affecting a production workload using the official Red Hat operator, my recommendation would be to raise the priority using the subscription account through the support channel.

**Comment by Anandnatraj** [comment]
@SSvilen which customer is this for? What's the criticality of the issue?

**Comment by SSvilen** [comment]
@Anandnatraj Aareon Deutschland Gmbh. We plan migration to 2022 on 8.10  (from Openshift 4.9 to 4.11) - so if there is hotfix released this or next week, that would be great..

**Comment by philipp1992** [comment]
when can we expect a fix for this ?
