### ISSUE TITLE
Install csi-proxy.exe to enable CSI plugins for Windows

### ISSUE THREAD

**Issue by ddebroy** [openshift/windows-machine-config-operator#140]
csi-proxy is a pre-requisite for CSI plugins (example: [AzureDisk](https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/master/deploy/example/windows/README.md#prerequisite), [AzureFile](https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/master/deploy/example/windows/README.md#prerequisite) and [GCE-PD](https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/pull/483)) for performing CSI node operations on Windows nodes. Please support installation of csi-proxy as a service (especially in Azure).

**Comment by aravindhp** [comment]
@ddebroy this is on our roadmap and we hope to get to it after we GA.

**Comment by alinaryan** [comment]
Hi @ddebroy - I will be closing this issue as we are tracking this in our [Storage Epic](https://issues.redhat.com/browse/WINC-26). Please follow along there.

**Comment by saifshaikh48** [comment]
/reopen

Keeping this open so its tracked on Github as well

**Comment by mtnbikenc** [comment]
Linking to the story for CSI Proxy.  https://issues.redhat.com/browse/WINC-681
/remove-lifecycle rotten
/lifecycle frozen

**Comment by mtnbikenc** [comment]
CSI-Proxy was added as part of https://issues.redhat.com/browse/WINC-1006 in WMCO 9.0.0.
/close
