### ISSUE TITLE
[RFE]: Windows Container support in air gapped environment - Status update?

### ISSUE THREAD

**Issue by jomeier** [openshift/windows-machine-config-operator#1403]
### Problem Statement

Windows Container support in air gapped environments?

### Feature description

Hi,

I'd like to ask about the status of air gapped Windows Container Support on OpenShift.

In our use case me must use Windows Containers in such a scenario. What is the reason, that this doesn't work?

Are there any workarounds possible to support Windows Containers in an air gapped environment? Any help will be highly appreciated.

I know that there is currently some "work" (https://issues.redhat.com/browse/WINC-936) occuring but I can't find any further status information for this important topic.

Thanks and best regards,

Josef

**Comment by alinaryan** [comment]
Hi @jomeier this is still high on the priority list - here's a link to the BU: https://issues.redhat.com/browse/OCPBU-96
Requests for status updates can be done there and our PM should be able to help.
