### ISSUE TITLE
WINC-987: Merge blocker for active release | branch:release-4.13

### ISSUE THREAD

**Issue by mansikulkarni96** [openshift/windows-machine-config-operator#1472]
### Description

[WINC-987](https://issues.redhat.com//browse/WINC-987) Windows Machine Config Operator 8.0.0 Release

**Comment by mtnbikenc** [comment]
/close
Temporarily closing to address blocker bug.

**Comment by mtnbikenc** [comment]
/close
Temporarily closing to address blocker bug.

**Comment by mtnbikenc** [comment]
Blocker bugs have merged.
/reopen

**Comment by mtnbikenc** [comment]
/close
Temporarily closing to address blocker bug.

**Comment by mtnbikenc** [comment]
Blockers have merged.
/reopen
