### ISSUE TITLE
WINC-1027: Merge blocker for active release | branch:release-4.12

### ISSUE THREAD

**Issue by alinaryan** [openshift/windows-machine-config-operator#1613]
### Description

[WINC-1027](https://issues.redhat.com/browse/WINC-1026) Windows Machine Config Operator 7.1.0 Release

**Comment by mtnbikenc** [comment]
Temporarily closing this issue to address blocker bug.
/close

**Comment by mtnbikenc** [comment]
Blocker bug merged.
/reopen

**Comment by aravindhp** [comment]
Temporarily closing this issue to allow backporting [OCPBUGS-13244](https://issues.redhat.com/browse/OCPBUGS-13244)
/close
