### ISSUE TITLE
[Bug]: Openshift 4.12 WMCO 7.0.1 - Wrong DNS Configuration

### ISSUE THREAD

**Issue by burkhat** [openshift/windows-machine-config-operator#1623]
### Attention

- [X] I am using the community version of WMCO

### Version

OCP

### Cluster Version

4.12

### Platform

vSphere

### Proxy

No

### WMCO Version

7.0.1

### Windows version

2022

### What happened?

Hello,

we've running Windows Workloads in our OCP environment.
 
Since the update from 4.11 to 4.12 and WMCO Operator 6.0.0 to 7.0.1 it is not possible resolve internal Cluster services.
With ipconfig /all we can see that the Host DNS Server are used within the container and not the cluster dns service: 100.123.0.10
DNS Servers . . . . . . . . . . . : 10.0.2.166
                                       10.0.23.159

We also tried to set it manually in the deployment but the container still using the Host DNS Server:
dnsConfig:
   nameservers:
     - 100.123.0.10
dnsPolicy: None

In the kubelet.conf of the Windows Host is set correctly:
![bcc35b10-509f-4969-b203-7591e75efe78](https://github.com/openshift/windows-machine-config-operator/assets/35066347/071a6021-9378-47a8-81c0-48774e319e13)

But in the Logfiles the cluster-dns variable is empty:
![4957b0f2-a991-4a78-aca2-4e9f57f99382](https://github.com/openshift/windows-machine-config-operator/assets/35066347/b4e13167-5344-4634-9709-79cd0e7790da)

At the moment our Windows Workloads cannot run.

### What did you expect to happen?

Set the correct ClusterDNS Server within the Container

### Steps to reproduce the issue

Update to 4.12 WMCO 7.0.1 and start a Windows Workload and try to resolve a Cluster internal Service

### Do you have a workaround for this issue?

No at the moment we don't have a workaround

**Comment by burkhat** [comment]
apiVersion: operator.openshift.io/v1
kind: Network
metadata:
  annotations:
    networkoperator.openshift.io/ovn-cluster-initiator: 10.0.38.46
  creationTimestamp: "2023-05-19T06:37:32Z"
  generation: 609
  name: cluster
  resourceVersion: "1614453"
  uid: 3e06d0d3-d581-40cc-ad7a-97108b7e1277
spec:
  clusterNetwork:
  - cidr: 100.122.0.0/16
    hostPrefix: 24
  defaultNetwork:
    ovnKubernetesConfig:
      egressIPConfig: {}
      gatewayConfig:
        routingViaHost: false
      genevePort: 6081
      hybridOverlayConfig:
        hybridClusterNetwork:
        - cidr: 100.127.0.0/16
          hostPrefix: 24
        hybridOverlayVXLANPort: 9898
      mtu: 1400
      policyAuditConfig:
        destination: "null"
        maxFileSize: 50
        rateLimit: 20
        syslogFacility: local0
    type: OVNKubernetes
  deployKubeProxy: false
  disableMultiNetwork: false
  disableNetworkDiagnostics: false
  logLevel: Normal
  managementState: Managed
  observedConfig: null
  operatorLogLevel: Normal
  serviceNetwork:
  - 100.123.0.0/16
  unsupportedConfigOverrides: null
  useMultiNetworkPolicy: false
status:
  conditions:
  - lastTransitionTime: "2023-05-20T06:35:26Z"
    status: "False"
    type: Degraded
  - lastTransitionTime: "2023-05-19T06:37:58Z"
    status: "True"
    type: Upgradeable
  - lastTransitionTime: "2023-05-19T06:37:58Z"
    status: "False"
    type: ManagementStateDegraded
  - lastTransitionTime: "2023-05-19T10:38:12Z"
    status: "False"
    type: Progressing
  - lastTransitionTime: "2023-05-19T06:38:32Z"
    status: "True"
    type: Available
  readyReplicas: 0
  version: 4.12.16

**Comment by kretzlaff** [comment]
We just ran into the same issue today using the exact same setup except we're using the Red Hat version and not the community one.
The kubelet config and log file look identical. We also have an empty `cluster-dns` flag.

**Comment by saifshaikh48** [comment]
Thanks for bringing this issue to attention. We will soon be releasing WMCO 7.1.0 which includes a pod DNS resolution fix

**Comment by aravindhp** [comment]
/close

Fixed by #1623
