### ISSUE TITLE
Prevent large windows container image pull timeouts with kubelet configuration

### ISSUE THREAD

**Issue by hatmarch** [openshift/windows-machine-config-operator#205]
Many Windows Container images are huge (upwards of 5GB) and this can cause trouble with the windows node kubelet.  I've observed with [this image](https://quay.io/repository/mhildenb/hplussports-win?tab=tags) running on (an admittedly small) Standard_D2s_v3 windows node configured by the WMCO.  The issue is that the container is so big that it can't be unpacked before the (default 1 minute) image pull progress deadline is exceeded.  This causes the pull to fail and be restarted.  The effect is that the container never runs.

I have confirmed that this issue can be remedied by increasing the --image-pull-progress-deadline of the windows node's Kubelet to something like 15m.  That is based on [this advice from google](https://cloud.google.com/kubernetes-engine/docs/how-to/creating-a-cluster-windows#image_pull_errors).

In my demo I used this [TaskRun](https://github.com/hatmarch/k8-for-windows-devs/blob/master/install/kube/tekton/taskrun/run-increase-pull-deadline.yaml) using [this task](https://github.com/hatmarch/k8-for-windows-devs/blob/master/install/kube/tekton/tasks/powershell-command.yaml) to run [this Powershell script](https://github.com/hatmarch/k8-for-windows-devs/blob/master/install/windows-nodes/scripts/image-pull-timeout.ps1) on the node after the WMCO finished its configuration.

Obviously, it would be better if the WMCO ansible playbook set the image timeout as part of the node setup.

**Comment by aravindhp** [comment]
> Obviously, it would be better if the WMCO ansible playbook set the image timeout as part of the node setup.

As per guidance from #sig-windows, the suggestion is for customers to prep the Windows worker VM image with the required container images. But we will collect more feedback to see if changes need to be made in this area.

PS: WMCO is a go operator

**Comment by hatmarch** [comment]
Thanks for the response and the correction about the inner workings of the operator.  

I don't quite understand why increased pull-progress-deadlines and preloading container images (or at least layers) are mutually exclusive.  Why not both?  

Even adding the option to have the operator adjust pull times (annotation in the MachineConfig CR or something like that) would be welcome.  Or upping the --image-pull-progress-deadline to 2m would probably be long enough in most cases.  In theory the change is fairly trivial given that the WMCO is already installing and configuring the kubelet.  

I think relying only on pre-caching the images on the VMs alone could cut against our overall DevOps story a bit.  Why does the Ops team need to be involved with knowing what the containers are that the Developers are going to use a priori?  Maybe in practice the beefier layers that cause the issue are common enough that pre-loading them doesn't require much back and forth between Dev and Ops but I would suspect that is not the case.

**Comment by aravindhp** [comment]
Sure, based on feedback we might increase the timeout, however I doubt we will ever make the value of the time out configurable as within OpenShift we try to not introduce too many knobs.
