### ISSUE TITLE
Documentation typo

### ISSUE THREAD

**Issue by CCChou** [openshift/windows-machine-config-operator#349]
Hi 

I have tried the windows node on vsphere and find out there's a typo about the example [unattend.xml](https://github.com/openshift/windows-machine-config-operator/blob/master/docs/unattend.xml).

At line 5 the xmlns:xsi and processorArchitecture there's some extra space would make the vm broken after sysprep.

**Comment by mansikulkarni96** [comment]
@CCChou, thanks for the report. I will open a PR to fix the issue.
