### ISSUE TITLE
SSH key in Windows golden image

### ISSUE THREAD

**Issue by fredrik-furtenbach** [openshift/windows-machine-config-operator#484]
I'm trying to configure Windows containers in OS 4.7 on vSphere, and I'm having some problems with my Windows golden image.

In the documentation you mention "Sysprep the VM. Use an unattend.xml that will maintain all the changes needed for the WMCO. The most important one being that the Administrator's home directory stays intact with the SSH public key." (https://github.com/openshift/windows-machine-config-operator/blob/master/docs/vsphere-prerequisites.md) and you provide an example unattend.xml.

The OpenShift 4.7 documentation references the same file, or a file much like it, with the text "An example unattend.xml is provided, which maintains all the changes needed for the WMCO. For example, the unattend.xml file must ensure the Administrator’s home directory stays intact with the SSH public key."

Well, I can't get this to work. Imageing the VM and using the image in a MachineSet works fine, but the .ssh key is not maintained and is missing from the finalized machine.

I could use some hints here. How are you maintaining the key in the finalized image?

**Comment by fredrik-furtenbach** [comment]
I followed this instruction instead and created a C:\ProgramData\ssh\administrators_authorized_keys instead of .ssh in the Administrator home directory, seems to be working fine.

https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_keymanagement#administrative-user

**Comment by jrvaldes** [comment]
@fredrik-furtenbach 

> I followed this instruction instead and created a C:\ProgramData\ssh\administrators_authorized_keys instead of .ssh in the Administrator home directory, seems to be working fine.
> 
> https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_keymanagement#administrative-user

Thanks for sharing this. As shown in the [Deploying the public key](https://github.com/openshift/windows-machine-config-operator/blob/master/docs/vsphere-golden-image.md#deploying-the-public-key) section of the documentation, the later approach is recommended. 

See commit https://github.com/openshift/windows-machine-config-operator/commit/c8ff886a27213d6d77f709fc741cac3cb42a21ee
