### ISSUE TITLE
kubelet.conf DNS server ip hardcoded

### ISSUE THREAD

**Issue by philipp1992** [openshift/windows-machine-config-operator#575]
we are using a custom subnet as hybridClusterNetwork of 100.124.0.0/16 and realized, that containers spawned on windows nodes always get the dns server 172.30.0.10 assigned.
In our case the kubernetes dns server would be 100.123.0.10 instead.

After looking into the windows nodes kubelet.conf, one can see, that the dns server ip 172.30.0.10 is hardcoded.

**Comment by saifshaikh48** [comment]
@philipp1992 Thank you for bringing this to our attention. I have created an issue to track this: [bz#1992228](https://bugzilla.redhat.com/show_bug.cgi?id=1992228). The team will work to prioritize this soon.

**Comment by philipp1992** [comment]
Awesome. You mention that the default gateway is wrong in the bugzilla which is not the case.its about the dns server.
Kind regards 
Philipp
