### ISSUE TITLE
Windows Server 2022 / Docker shim deprecation

### ISSUE THREAD

**Issue by SSvilen** [openshift/windows-machine-config-operator#830]
Hello,

since I'm not sure where exactly I should post that kind of questions I am doing it here.
- For which version of OpenShift is the support for Server 2022 planned? My guess would be 2 version from now. 
- Do you plan to support Dockershim beyond Kubernetes version 1.24? Or you plan also to drop the support also with that version.
- Which leads me to my next question: What are the plans for officially supporting ContainerD?

**Comment by aravindhp** [comment]
>     * For which version of OpenShift is the support for Server 2022 planned? My guess would be 2 version from now.

We currently working on adding support for Windows Server 2022. We are in the process of deciding the OpenShift versions where the support will be added.
 
>     * Do you plan to support Dockershim beyond Kubernetes version 1.24? Or you plan also to drop the support also with that version.

We do not plan to support Dockershim beyond 1.24

>     * Which leads me to my next question: What are the plans for officially supporting ContainerD?

Adding support for ContainerD is currently underway.

**Comment by aravindhp** [comment]
/close

Please follow [Windows Containers: containerd](https://issues.redhat.com/browse/WINC-505) and [Include support for Windows Server Version 2022 in WMCO/WMCB](https://issues.redhat.com/browse/WINC-602)
