### ISSUE TITLE
Restart docker service after hybrid-overlay-node process has been started

### ISSUE THREAD

**Issue by jomeier** [openshift/windows-machine-config-operator#94]
Hi,

after starting the hybrid-overlay-node process on the windows node, the docker service must be restarted (and maybe also the kube-proxy service).

Without that Docker does not now about the new overlay networks.

Greetings,

Josef

**Comment by gmarkley-VI** [comment]
Thank you this has been addressed in our upcoming operator.

**Comment by aravindhp** [comment]
Fixed by https://github.com/openshift/windows-machine-config-operator/pull/104 and https://github.com/openshift/windows-machine-config-bootstrapper/pull/233
